# Generated by Django 5.2.3 on 2025-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('r_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('math', models.FloatField(blank=True, null=True)),
                ('literature', models.FloatField(blank=True, null=True)),
                ('foreign_lang', models.FloatField(blank=True, null=True)),
                ('physics', models.FloatField(blank=True, null=True)),
                ('chemistry', models.FloatField(blank=True, null=True)),
                ('biology', models.FloatField(blank=True, null=True)),
                ('history', models.FloatField(blank=True, null=True)),
                ('geography', models.FloatField(blank=True, null=True)),
                ('civic_education', models.FloatField(blank=True, null=True)),
                ('foreign_lang_code', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
